export const PERMISSION_TYPES = {
  // Restaurant Management
  MANAGE_MENU: "MANAGE_MENU",
  MANAGE_QR_CODES: "MANAGE_QR_CODES",
  MANAGE_GROUPS: "MANAGE_GROUPS",
  MANAGE_ADS: "MANAGE_ADS",
  MANAGE_PACKAGES: "MANAGE_PACKAGES",
  MANAGE_ORDERS: "MANAGE_ORDERS",

  // Customer Features
  CUSTOMER_LOYALTY: "CUSTOMER_LOYALTY",
  CUSTOMER_NOTIFICATIONS: "CUSTOMER_NOTIFICATIONS",
  CUSTOMER_GIFTS: "CUSTOMER_GIFTS",

  // Analytics & Reports
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  EXPORT_DATA: "EXPORT_DATA",

  // Advanced Features
  CUSTOM_BRANDING: "CUSTOM_BRANDING",
  API_ACCESS: "API_ACCESS",
  MULTI_LOCATION: "MULTI_LOCATION",

  // Limits
  MAX_MENU_ITEMS: "MAX_MENU_ITEMS",
  MAX_ADS: "MAX_ADS",
  MAX_PACKAGES: "MAX_PACKAGES",
  MAX_GROUP_MEMBERS: "MAX_GROUP_MEMBERS",
} as const;

export const PERMISSION_LABELS = {
  [PERMISSION_TYPES.MANAGE_MENU]: "Manage Menu",
  [PERMISSION_TYPES.MANAGE_QR_CODES]: "Manage QR Codes",
  [PERMISSION_TYPES.MANAGE_GROUPS]: "Manage Groups",
  [PERMISSION_TYPES.MANAGE_ADS]: "Manage Ads",
  [PERMISSION_TYPES.MANAGE_PACKAGES]: "Manage Packages",
  [PERMISSION_TYPES.MANAGE_ORDERS]: "Manage Orders",
  [PERMISSION_TYPES.CUSTOMER_LOYALTY]: "Customer Loyalty",
  [PERMISSION_TYPES.CUSTOMER_NOTIFICATIONS]: "Customer Notifications",
  [PERMISSION_TYPES.CUSTOMER_GIFTS]: "Customer Gifts",
  [PERMISSION_TYPES.VIEW_ANALYTICS]: "View Analytics",
  [PERMISSION_TYPES.EXPORT_DATA]: "Export Data",
  [PERMISSION_TYPES.CUSTOM_BRANDING]: "Custom Branding",
  [PERMISSION_TYPES.API_ACCESS]: "API Access",
  [PERMISSION_TYPES.MULTI_LOCATION]: "Multi Location",
  [PERMISSION_TYPES.MAX_MENU_ITEMS]: "Max Menu Items",
  [PERMISSION_TYPES.MAX_ADS]: "Max Ads",
  [PERMISSION_TYPES.MAX_PACKAGES]: "Max Packages",
  [PERMISSION_TYPES.MAX_GROUP_MEMBERS]: "Max Group Members",
} as const;

export const PERMISSION_CATEGORIES = {
  MANAGEMENT: [
    PERMISSION_TYPES.MANAGE_MENU,
    PERMISSION_TYPES.MANAGE_QR_CODES,
    PERMISSION_TYPES.MANAGE_GROUPS,
    PERMISSION_TYPES.MANAGE_ADS,
    PERMISSION_TYPES.MANAGE_PACKAGES,
    PERMISSION_TYPES.MANAGE_ORDERS,
  ],
} as const;
